name: Deploy to GCP App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Authenticate with GCP
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: lateral-origin-380509
        service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Install dependencies
      run: npm install

    - name: Deploy to App Engine
      run: |
        gcloud app deploy --quiet
