name: hello-world

on: [push,pull_request]
   
jobs:
  build:

    runs-on: ubuntu-latest
 

    steps:
    - name: checkout
      uses: actions/checkout@v3
      id: 'auth'
    - name: install dependencies
      run: npm install
    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        
        version: v1
        project_id:  ${{ secrets.PROJECT_ID}}
        credentials: ${{ secrets.SERVICE_ACCOUNT_KEY}}
    
