name: Deploy to GCP App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Configure Google Cloud SDK
        uses: google-github-actions/configure-gcloud@v0

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        

      - name: Install dependencies
        run: npm install

      - name: Deploy to App Engine
        run: |
          gcloud app deploy --quiet
